### ISSUE TITLE
Create new wallet branding

### ISSUE THREAD

**Issue by RubenMattan** [threefoldfoundation/tf_app#279]
## Requests
- GET `/api/plugins/tff_backend/v1.0/wallet/transactions?address=`
- POST `/api/plugins/tff_backend/v1.0/wallet/create_signature_data`
- POST `/api/plugins/tff_backend/v1.0/wallet/transactions`

## Receive
Create QR Code with json `{'address': 'XXX': 'amount': 'XXX'}`

## Pay
Pay to address or scan QR Code
steps:
1. create signature data
2. get transaction data
3. sign transaction data
4. create transaction

**Comment by lucasvanhalst** [comment]
Is there any design for this? I assume it will look a lot different than the current wallet since it doesn't need to be generic

**Comment by RubenMattan** [comment]
![Bitcoin wallet](https://cdn57.androidauthority.net/wp-content/uploads/2016/11/Bitcoin-Wallet-by-Blockchain-Luxembourg-screenshot-840x472.jpg)

**Comment by lucasvanhalst** [comment]
See https://github.com/threefoldfoundation/tf_app/pull/287
