### ISSUE TITLE
copy address of the wallet isn't working

### ISSUE THREAD

**Issue by islamTaha12** [threefoldfoundation/tf_app#303]
**steps**
- `services>wallet` 
- Click to copy the address
- Try to `paste` it 

**actual result**
- Copy address to the clipboard isn't working

**Comment by RubenMattan** [comment]
on what device did you test this?

**Comment by islamTaha12** [comment]
@RubenMattan Nexus android 6.0.1

**Comment by bart-at-mobicage** [comment]
Android
Hardware model: Nexus 5
Operating system version: 23

**Comment by islamTaha12** [comment]
working with 
`2.1.3919.A`
