### ISSUE TITLE
QR scanner isn't working

### ISSUE THREAD

**Issue by islamTaha12** [threefoldfoundation/tf_app#305]
**Device**
Nexus - Android 6.0.1
Asus Zenpad s8 - Android 6.0.1

**Description**
Using `scan threefold staging QR code` to scan an address isn't working.

**Comment by bart-at-mobicage** [comment]
It's not intended to work with this Scan button, but I understand that it's not logical. 
Perhaps we should hide the Scan button, @FastGeert, since the Friend functionality was removed from the app as well.
