### ISSUE TITLE
steal tokens from the network

### ISSUE THREAD

**Issue by islamTaha12** [threefoldfoundation/tf_app#308]
**Description**
The sender has ~55k TFT then Receiver tries to receive all tokens from the sender. Receiver generated a QR code to get all tokens-1 from the sender. Sender scans the QR code from the receiver and try to send the amount to it > I pressed `cancel` while the app tried to do the transaction then I pressed `send` again.

**Hint**
I did it 4 times so I got ~200K from the network

**Actual result**
Sender app status
![image](https://user-images.githubusercontent.com/17981089/38087023-e3ce3af4-3356-11e8-9f64-3ca93d8c98d5.png)

Receiver app status
![image](https://user-images.githubusercontent.com/17981089/38086957-a1fbc434-3356-11e8-973f-1836bfa0c0a8.png)

**Comment by lucasvanhalst** [comment]
seems like it's returning the same transaction 4 times for some reason
https://staging-tff-backend.appspot.com/api/plugins/tff_backend/v1.0/wallet/transactions?address=01f7ad94d68363e76c7ae5b7150b104ae12296da74a8f75014db7bb83a740d2b776b3149451e40 vs https://explorer.testnet.threefoldtoken.com/explorer/hashes/01f7ad94d68363e76c7ae5b7150b104ae12296da74a8f75014db7bb83a740d2b776b3149451e40

**Comment by RubenMattan** [comment]
PR: https://github.com/threefoldfoundation/tf_app/pull/309
