### ISSUE TITLE
unknown error has occurred after trying to re-send tokens

### ISSUE THREAD

**Issue by islamTaha12** [threefoldfoundation/tf_app#320]
**steps**
- Scan a QR code to send money.
- Press 'send'
- Wait till "Confirmation Transaction" be active then press "Cancel". App will return you back to the `QR Code Scanner` screen.
- Scan the QR again and try to `send` the tokens.

**Actual Result**
![image](https://user-images.githubusercontent.com/17981089/38621599-7aa9028e-3da1-11e8-81cb-5d8cca2cfde7.png)

**Comment by lucasvanhalst** [comment]
Seems like the issue here was that the testnet was down again
