### ISSUE TITLE
There are still some users with the old wallet

### ISSUE THREAD

**Issue by RubenMattan** [threefoldfoundation/tf_app#324]
2018-04-30 22:14:26.323 CEST
Request identity: xxx@itsyou.online:em-be-threefold-token (ios)
MissingArgumentException: memo is a required argument in function receive_payment!

**Comment by lucasvanhalst** [comment]
We'll have to clean up the grants stuff:
- [ ] Nobody should have the 'public' or 'members' grants anymore
- [ ] Everybody should see all menu items that have the 'members' Role now
- [ ] Remove the 'members', 'public' and 'invited' roles.
