### ISSUE TITLE
Live chat

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#332]
When pressing 'support' on iOS, the back button shows 'Live chat'. When pressing this back button, we see a screen with a CLOSE button. I thought this close button was only for backwards compatibility. Is exitApp not called?

<img src="https://user-images.githubusercontent.com/17762105/43313815-71f2b27c-9191-11e8-9837-b46b9b9513df.png" width="250px"> <img src="https://user-images.githubusercontent.com/17762105/43313820-75524dec-9191-11e8-856b-bcf4c5ad99b6.png" width="250px">

**Comment by lucasvanhalst** [comment]
if the ios version is > 2981 then it is called, else not
