### ISSUE TITLE
Add 'purchase tokens' button to Mazraa

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#334]
Add 'Purchase Tokens' button Flow:

Select currency
Select amount in $, €, BTC (whichever they chose)
Select if they want to wire to a Dubai account or European account
Sign the contract
ONLY IF KYC HAS ALREADY BEEN VERIFIED AND APPROVED (not if they choose to pay with BTC). If not, show message: Before purchasing tokens, we would like to ask you to finish the Know Your Customer procedure first. (button: Finish KYC or Cancel).

**Comment by sabrinasadik** [comment]
When can this be fixed? - needs priority

**Comment by bart-at-mobicage** [comment]
Normally, I'll be able to do this tomorrow.

**Comment by lucasvanhalst** [comment]
So what about the address? Else we have to contact the user again

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, is there an up to date version of https://docs.google.com/document/d/1Y7RtA8C99a6fKbf1In3SBH1TlbFG36ap79kJVVeL0-A/edit that we can use as contract?

Right now we have this version:

> | **Name of the purchaser**    | {{ full_name }}                      |
> |------------------------------|--------------------------------------|
> | **Address of the purchaser** | {{ address }}                        |
> | **Purchase Amount**          | **{{ amount }}** {{ currency_full }} |
> | **Purchase Price**           | {{ price_words }} U.S. Dollar ({{ price }} US $) per iTFT |
> 
> This agreement (hereinafter referred to as the “**Agreement**”) is entered into on **{{ effective_date }}** (the “**Effective Date**”), by and between:
> 
> The purchaser mentioned above (the “**Purchaser**”);  
> and  
> **ThreeFold FZC**, a free zone establishment with License No: 17194 with its principal place of business at Q1-07-038/B SAIF Zone, United Arab Emirates, PO Box 514608; hereinafter referred to as the “**Company**”;
> 
> Collectively referred to in this Agreement as the “**Parties**”, each referred to as a “**Party**”.
> 
> Before its Private Token Offering (“**PTO**”), the Threefold Foundation is launching an Internal Token Offering (“**ITO**”) for friends, family and ambassadors. In exchange for the payment of the Purchase Amount, the Company hereby issues to the Purchaser certain digital tokens (the “**internal ThreeFold Tokens**” or “**iTFT's**”), which on the occurrence of the PTO will be exchanged against digital tokens of the ThreeFold Foundation (the “**ThreeFold Tokens**” or “**TFT's**”), subject to the terms set forth below.
> 
> **1. Conditionality**
> 
> The present Agreement is entered into between the Parties subject to the Purchaser’s completion of the Company’s “know-your-customer” verification process (“**KYC**”). Customer agrees to cooperate in good faith with the Company and to provide such information as may be reasonably requested by the Company in order to complete such KYC. The Company reserves the right not to enter into, or to terminate, this Agreement based on any issue that may arise as a result of such KYC (including, but not limited to, possible non-compliance with applicable anti-money laundering legislation).
> 
> **2. Internal Token Offering**
> 
> Subject to the terms set out hereinafter, including Purchaser’s payment of the entire Purchase Amount, the Company sells and transfers to the Purchaser, and the Purchaser accepts and acquires, the entire rights and title to such number of iTFT's corresponding to the above mentioned Purchase Amount (converted, as the case may be, into US Dollars as per Section 4 below) divided by the Purchase Price.
> 
> Upon Company's reasonable request, the Purchaser will provide all information, including a network address to which the iTFT's will be sent upon receipt of the Purchase Amount. The Purchaser will furthermore execute and deliver to the Company any and all other transaction documents related to this Agreement as may be reasonably requested by the Company, including verification of non-US/China/Canada person status under the applicable securities laws.
> 
> **3. Exchange against TFT's**
> 
> If and when the ThreeFold Foundation’s Private Token Offering takes place, any and all iTFT's held by the Purchaser will automatically be exchanged against a corresponding number of TFT's on the first day of the PTO.  
> 
> **4. Lock-up Period**
> 
> Unless explicitly agreed to by the Company or the ThreeFold Foundation, Purchaser will not be allowed to sell or transfer the iTFT's purchased under this Agreement for a period of six months after the date of this Agreement. Any TFT’s acquired by Purchaser upon conversion of its iTFT’s into TFT’s shall be made subject to the same lock-up period as the original iTFT’s acquired by Purchaser.
> 
> During such six months lock-up period, however, the Purchaser shall still be entitled to:
> 
>  - (a)	use the iTFT's and/or TFT's to purchase IT capacity on the ThreeFold Grid through the ThreeFold Directory; and
> 
>  - (b)	transfer iTFT's and/or TFT’s to a person or entity that already owns iTFT’s or TFT’s immediately prior to such transfer.
> 
> **5. Payment**
> 
> The Company will accept payment for the iTFT's purchased under this Agreement in U.S. Dollars, Euro, Pound Sterling, United Arab Emirates Dirham and Bitcoin. Purchaser shall make the required payment to the Company in consideration for Purchaser’s purchase of the iTFT’s pursuant to the Agreement by wire transfer to the Company within three business days. The payment information will be provided in the ThreeFold app.
> 
> For purposes of this Agreement, the value of the Purchase Amount shall be deemed in U.S. Dollar even when the Purchaser pays in any of the other currencies mentioned above.
> 
> Conversion of other currencies stated above to U.S. Dollars will be made as follows:
> 
> - For purchases made in Bitcoin, on the day on which the Bitcoin payment has been received by the Company in its Wallet, the Purchase Amount will be converted in AED first at the conversion rate quoted on the website of BitOasis Technologies FZE, and then immediately thereafter from AED in U.S. Dollars at the conversion rate quoted on the website of Oanda.com, both on such date at 11.59 PM Gulf Standard Time.
> - For purchases made in EUR, GBP or AED, the Purchase Amount will be converted in U.S. Dollars at the following conversion rate:
>     - 1 U.S. Dollar = {{ conversion['EUR'] }} Euro;
>     - 1 U.S. Dollar = {{ conversion['GBP'] }} Pound Sterling;
>     - 1 U.S. Dollar = 3.67 United Arab Emirates Dirham.
> 
> 
> **6. Disclaimer**
> 
> **THE COMPANY MAKES NO WARRANTY WHATSOEVER, NEITHER IN ITS OWN NAME NOR IN THE NAME OF THE THREEFOLD FOUNDATION, WITH RESPECT TO THE iTFT's AND/OR THE TFT's, INCLUDING ANY (i) WARRANTY OF MERCHANTABILITY; (ii) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (iii) WARRANTY OF TITLE; OR (iv) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER ARISING BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE. EXCEPT AS EXPRESSLY SET FORTH HEREIN, PURCHASER ACKNOWLEDGES THAT IT HAS NOT RELIED UPON ANY REPRESENTATION OR WARRANTY MADE BY THE COMPANY, OR ANY OTHER PERSON ON THE COMPANY'S BEHALF.**
> 
> **7. Purchaser representations**
> 
> (A) The Purchaser has full legal capacity, power and authority to execute and deliver this Agreement and to perform its obligations hereunder. This Agreement constitutes valid and binding obligation of the Purchaser, enforceable in accordance with its terms, except as limited by bankruptcy, insolvency or other laws of general application relating to or affecting the enforcement of creditors’ rights generally and general principles of equity.
> 
> (B) The Purchaser is NOT a resident or citizen of any of the following countries:  
> 
> - People’s Republic of China
> - South Korea
> - North Korea
> - Singapore
> 
> (C) The Purchaser is NOT a target person or entity under any restrictive measures in the framework of the EU Common Foreign and Security Policy.
> 
> (D) The Purchaser is, and has at all times been, in compliance in all material respects with each legal requirement that are applicable to him or her, or the ownership of their assets, relating to money laundering;
> 
> (E) The Purchaser has been advised that this Agreement, the iTFT's and/or the TFT's (such tokens hereinafter: the “**Tokens**”) may qualify as a security and that the offers and sales of this Agreement and/or the Tokens have not been registered under any country’s securities laws and, therefore, cannot be resold except in compliance with the applicable country’s laws. The Purchaser is executing this Agreement for its own account, not as a nominee or agent. The Purchaser has such knowledge and experience in financial and business matters that the Purchaser is capable of evaluating the merits and risks of such investment, is able to incur a complete loss of such investment without impairing the Purchaser’s financial condition and is able to bear the economic risk of such investment for an indefinite period of time.
> 
> (F) The Purchaser understands that the Tokens involve risks, all of which the Purchaser fully and completely assumes, including, but not limited to, the risk that (i) the technology associated with the Threefold Grid, 0-Nodes and/or related Threefold products will not function as intended; (ii) the Threefold Foundation project will not be completed; (iii) Threefold Foundation will fail to attract sufficient interest from key stakeholders; and (iv) the Company and/or the ThreeFold Foundation may be subject to investigation and punitive actions from governmental authorities. The Purchaser understands and expressly accepts that the Tokens will be created and delivered to the Purchaser at the sole risk of the Purchaser on an “AS IS” and “UNDER DEVELOPMENT” basis. The Purchaser understands and expressly accepts that the Purchaser has not relied on any representations or warranties made by the Company outside of this Agreement, including, but not limited to, conversations of any kind, whether through oral or electronic communication, or any white paper. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, THE PURCHASER ASSUMES ALL RISK AND LIABILITY FOR THE RESULTS OBTAINED BY THE USE OF ANY TOKENS AND REGARDLESS OF ANY ORAL OR WRITTEN STATEMENTS MADE BY THE COMPANY, BY WAY OF TECHNICAL ADVICE OR OTHERWISE, RELATED TO THE USE OF THE TOKENS.
> 
> (G) The Purchaser understands that Purchaser has no right against the Company or any other Person except in the event of the Company’s breach of this Agreement or intentional fraud. THE COMPANY’S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER ARISING OUT OF OR RELATED TO BREACH OF CONTRACT, TORT OR OTHERWISE, SHALL NOT EXCEED THE TOTAL OF THE AMOUNTS PAID TO THE COMPANY PURSUANT TO THIS AGREEMENT. NEITHER THE COMPANY NOR ITS REPRESENTATIVES SHALL BE LIABLE FOR CONSEQUENTIAL, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR ENHANCED DAMAGES, LOST PROFITS OR REVENUES OR DIMINUTION IN VALUE, ARISING OUT OF OR RELATING TO ANY BREACH OF THIS AGREEMENT.
> 
> (H) The Purchaser understands that Purchaser bears sole responsibility for any taxes as a result of the matters and transactions the subject of this Agreement, and any future acquisition, ownership, use, sale or other disposition of Tokens held by the Purchaser. To the extent permitted by law, the Purchaser agrees to indemnify, defend and hold the Company or any of its affiliates, employees or agents (including developers, auditors, contractors or founders) harmless for any claim, liability, assessment or penalty with respect to any taxes (other than any net income taxes of the Company that result from the sale of Tokens to the Purchaser pursuant to Section 1 of the Agreement) associated with or arising from the Purchaser’s purchase of Tokens hereunder, or the use or ownership of Tokens.
> 
> **8. Electronic signatures**
> 
> Each Party agrees that the electronic signatures, whether digital or encrypted, of the Parties included in this Agreement or any other agreement entered into between the Parties after the Effective date, are intended to authenticate such agreement and to have the same force and effect as manual signatures.  Delivery of a copy of this Agreement or any other document contemplated hereby bearing an original or electronic signature by facsimile transmission, by electronic mail in “portable document format” (“.pdf”) form, or by any other electronic means intended to preserve the original graphic and pictorial appearance of a document, will have the same effect as physical delivery of the paper document bearing an original or electronic signature.
> 
> **9. Assignment**
> 
> The Purchaser agrees that the Company may transfer and assign the Agreement in its discretion provided notice of such assignment is sent to the Purchaser within fifteen days of such assignment. The Purchaser may not transfer, sell or assign its rights and obligations under this Agreement.
> 
> **10. Amendments**
> 
> No amendment modifying, adding to or omitting from, or terminating this Agreement will be binding upon a Party unless made in writing and signed by or in the name of the Parties involved.
> 
> **11. Partial Invalidity**
> 
> The nullity of one of the provisions of this Agreement shall have no bearing on the validity of the other provision of this Agreement.
> 
> In such case the Parties to this Agreement shall in good faith negotiate on the provisions of this Agreement so that the same economic balance between the rights and obligations of the Parties to this Agreement are safeguarded to the same extent as if the invalid provision had been valid.
> 
> **12. Governing Law**
> 
> This Agreement is subject to the laws of Sharjah (United Arab Emirates).
> 
> **13. Jurisdiction**
> 
> Any dispute which may arise between the Parties in relation to the validity, the interpretation or the execution of this Agreement will be submitted to the exclusive jurisdiction of the Courts of Sharjah, United Arab Emirates.
> 
> Signed on the Effective Date in two originals, each of the Parties acknowledging having received one original.
> 
> | The Company   | The Purchaser   |
> |---------------|-----------------|
> | ThreeFold FZC | {{ full_name }} |
>

**Comment by VonSub** [comment]
Purchase Agreements will be done today, since we also need the purchase flow for BetterToken.
Will keep you guys posted here.

**Comment by lucasvanhalst** [comment]
Since I've heard we will not do this after all I'm closing this
