### ISSUE TITLE
Remove old BetterToken under TF Ecosystem

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#337]
Right now I find 2 - needs to be the new one (with round logo). Other one needs to be deleted.

**Comment by sabrinasadik** [comment]
![photo_2018-07-26_21-13-00](https://user-images.githubusercontent.com/31733464/43318760-57944e98-91a2-11e8-9f34-29d0b090224a.jpg)

**Comment by bart-at-mobicage** [comment]
#344
