### ISSUE TITLE
Delete 'ThreeFold Foundation' under TF Foundation

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#340]
TF Foundation is now split up under

Decentralized exchange
ThreeFold Grid
ThreeFold Token
No others needed here

**Comment by sabrinasadik** [comment]
![photo_2018-07-26_21-07-52](https://user-images.githubusercontent.com/31733464/43318768-61552632-91a2-11e8-90dd-7d2504864ccc.jpg)

**Comment by bart-at-mobicage** [comment]
#344
