### ISSUE TITLE
Remove Rogerthat T&C's [4h]

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#341]
![photo_2018-07-26_21-04-54](https://user-images.githubusercontent.com/31733464/43318783-7516ed72-91a2-11e8-82e1-4ab39b9305e6.jpg)

**Comment by sabrinasadik** [comment]
Do we have TF T&C's? If not, we need to delete this until we have TF T&C's.

**Comment by bart-at-mobicage** [comment]
Configure the TF app to skip the T&C's. Add this configuration if it didn't exist yet.

**Comment by RubenMattan** [comment]
Fixed by https://github.com/our-city-app/mobicage-backend/commit/01353dbeb078a8dbbdde585e56fe65ce6de0a7be

Steps:
- Deploy
- Save settings with tos_enabled set to False for the apps you need.
