### ISSUE TITLE
TF Foundation cleanup

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#344]
- [x] Rename the "Threefold Foundation" service (`service-4bf3bdf1-8628-491d-849b-698d7503c68a@rogerth.at`) to "ThreeFold Token"
  - [x] Remove `service-c048fa6c-0160-4f36-8c97-f6cf845868e7@rogerth.at` and unfollow all users
    - [x] Remove its customer `5698326444376064`
- [x] Remove the Calendar service menu item (of service `service-4bf3bdf1-8628-491d-849b-698d7503c68a@rogerth.at`), and replace with OCA agenda (double check if the poke tag is the same, for the shortcut in the sidebar)
  - [ ] Configure that events of all other service are included in the agenda of the new ThreeFold Token (CityAppProfile.gather_events)
- [x] Move the 'purchase tokens' and 'kyc' menu items to the Mazraa service (`service-e82ea218-16d7-4db3-880b-e1b04fe71c0d@rogerth.at`). Make sure the backend allows this. 
- [x] Move the 'node status' menu item to the ThreeFold Grid service (`service-4bf8aa06-753a-44da-a82f-40829fba4a4a@rogerth.at`)
- [x] Remove the 'become a hoster' menu item

**Comment by lucasvanhalst** [comment]
TODO:
- delete Customer 5698326444376064
- delete duplicated Customer of bettertoken (named 'old bettertoken bvba')
- Configure that events of all other service are included in the agenda of the new ThreeFold Token (CityAppProfile.gather_events)
