### ISSUE TITLE
User-based group chats [15d]

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#351]
- Change the plus icon to a pen (like telegram/whatsapp/messenger/...) (iOS only)
- Make it possible to 
  - start a group chat
  - set/change an avatar and topic (admin)
  - add/invite friends to this group chat after it's created (admin)
  - change admins (admin)
  - remove members (admin)

**Comment by RubenMattan** [comment]
backend / android are ready to be validated
iOS should better be done by another person the validate all the code etc..
