### ISSUE TITLE
Add descriptive first row to add new friends [3h]

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#359]
See telegram
Add a first row list with a + icon to the friends, to add new friends.

**Comment by RubenMattan** [comment]
Telegram for Desktop or Android doesn't has this, can you add a screenshot?

**Comment by bart-at-mobicage** [comment]
![image-1-1](https://user-images.githubusercontent.com/17762105/44843163-ecc83780-ac47-11e8-8a14-6b38f85c7d87.jpg)
