### ISSUE TITLE
Can't see what you're typing while registering email 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#363]
![photo_2018-10-03_11-35-07](https://user-images.githubusercontent.com/31733464/46402634-99db1780-c700-11e8-9b21-c0a7aecd0bd2.jpg)
This happened when I made a typo in my email address and went back to the previous screen to correct it. Couldn't see what I'm typing.

**Comment by lucasvanhalst** [comment]
https://github.com/our-city-app/mobicage-android-client/pull/66

**Comment by lucasvanhalst** [comment]
will be fixed once we create a new version of the app
