### ISSUE TITLE
Small button in transaction confirmation screen

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#372]
![image 2018-10-03 15 19 01](https://user-images.githubusercontent.com/17762105/46412752-a91d8d80-c71f-11e8-8a11-1273e7aca55a.jpg)

**Comment by lucasvanhalst** [comment]
https://github.com/threefoldfoundation/rivine-wallet/commit/9f669eb782bf0151715c1198a78feda678549bae
