### ISSUE TITLE
Incorrect transaction amounts shown

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#375]
I ordered something of 1.80 TFT. The transaction confirmation screen showed "**Amount: 0**". The order confirmation showed "**3.50 TFT has been paid**".

Happened only once. 

<img src="https://user-images.githubusercontent.com/17762105/46936078-721f7400-d05d-11e8-8996-3bda1fdd6f93.PNG" width="300px"> <img src="https://user-images.githubusercontent.com/17762105/46936077-721f7400-d05d-11e8-80aa-e33d56bc4264.PNG" width="300px">

**Comment by bart-at-mobicage** [comment]
The receiver "lost" 0.1 TFT?

<img src="https://user-images.githubusercontent.com/17762105/46936582-18b84480-d05f-11e8-9bf2-fd96c139c670.PNG" width="300px"> <img src="https://user-images.githubusercontent.com/17762105/46936581-18b84480-d05f-11e8-9e2b-0d420d15c187.PNG" width="300px">

**Comment by bart-at-mobicage** [comment]
Apparently this happens the address of the merchant equals your own address. So I was basically paying TFTs to myself ^^

**Comment by lucasvanhalst** [comment]
since I don't know another way to know who is the receiver and who is the sender the outputs are filtered by address. I _could_ add special cases in case the address is the same but is this really necessary ?
