### ISSUE TITLE
ThreeFold Love: Donations

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#376]
- [x] Add a message flow to `service-377b6342-c724-4d98-b7ff-47857eea4cb9` with menu item label 'Give Love'
- Step 1: Text line
  - Message: You can support ThreeFold Love by donating tokens. 100% of your donation helps empower communities across the globe, one node at a time.
  - Placeholder: Enter the amount of ThreeFold Tokens you want to donate
  - Keyboard type: number
  - Buttons: Donate / Cancel
- Step 2: Pay
  - Address: `0115526ab70c03cf46ce295f9fc0c71edbdfefce0d3b1a6375f934ee6396ad37ae5fd3dc1dcf5d`
  - Amount: get it from previous step

- [x] To test, add this flow to `service-e1c0b65a-0241-4c79-98d8-ca7fb0761d82@rogerth.at` too (test address of this service can be found in the 'mobile payments' step)

**Comment by lucasvanhalst** [comment]
added to the staging merchant
service-377b6342-c724-4d98-b7ff-47857eea4cb9 does not exist

**Comment by bart-at-mobicage** [comment]
I've updated the address and payment provider in the TF Love service. Once the Android and iOS apps are updated, we'll update the appIds of the TF Love service to `['em-be-threefold-token']`
