### ISSUE TITLE
My wallet is empty (TF Testnet)

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#377]
I reinstalled the app, tested payments, everything worked. However, when I opened my wallet, it didn't show any transactions.

Check if the production wallet has the same issue.

<img width="488" alt="screen shot 2018-10-21 at 15 48 11" src="https://user-images.githubusercontent.com/17762105/47267872-97bee880-d549-11e8-9fcb-605d7880fecd.png">

**Comment by lucasvanhalst** [comment]
Did you create a new version of the staging app? the embedded app id in the sidebar has been changed so most likely it's using the 'real' network in your simulator
