### ISSUE TITLE
Wallets page asks to update the app while already at the latest version

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tf_app#379]
ios version: 12.1 (16B92) iphone 6
threefold app version:  2.1.3083.i

**Comment by bart-at-mobicage** [comment]
@lucasvanhalst, lets start with logging the version we receive from the app, then we can investigate further via log forwarding.

**Comment by lucasvanhalst** [comment]
Seems to be fixed by pushing a new version of the wallet with some added logging

**Comment by RubenMattan** [comment]
Logging was added, bug was not identified yet. When another issue occurs we will investigate
