### ISSUE TITLE
Transaction confirmation screen is empty

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#380]
The wallet executes the following requests:
- /explorer
- /explorer/blocks/<height>
- /explorer/hashes/<address>

Somehow, one of these request must fail.

- [ ] We need logging in the wallet before/after executing the request to be able to see which request fails/times out.
- [ ] Show a spinner above the 'confirm transaction' button until the response is received.

![2018-11-19 12 04 42](https://user-images.githubusercontent.com/17762105/48703216-53c80d80-ebf3-11e8-9aea-e98d55c5a134.jpg)

**Comment by sabrinasadik** [comment]
Problem in app seems to be solved.

**Comment by robvanmieghem** [comment]
I still do not like it, the  timeout is 5 seconds and you  try multiple.  If every explorer fails, it  should at least be logged as an error.

**Comment by lucasvanhalst** [comment]
I've added some logging and fixed the loading spinner not showing up for the first request
