### ISSUE TITLE
Unknown error when loading transactions

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#382]
At this moment, explorer.threefoldtoken.com doesn't work. I don't know why the wallet doesn't fallback to another explorer, because the others work. Or maybe there is another root cause.

My wallet doesn't have any problem.

![2018-12-31 11 41 14](https://user-images.githubusercontent.com/17762105/50558761-1629ca80-0cf1-11e9-9bf0-f71cffd5801e.jpg)

**Comment by lucasvanhalst** [comment]
I've found and fixed the issue so if we were to rebuild master it would be fixed

**Comment by RubenMattan** [comment]
Will be released with ERC20 transactions
