### ISSUE TITLE
Implement ERC20 transactions

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#383]
See 
https://github.com/threefoldfoundation/tfchain/blob/bridge_tft_erc20/doc/erc20.md
https://github.com/threefoldfoundation/tfchain/blob/bridge_tft_erc20/doc/transactions.md
https://github.com/threefoldtech/home/issues/56

**Comment by RubenMattan** [comment]
Blocked on unfinished work from threefold

**Comment by bart-at-mobicage** [comment]
@sabrinasadik 

Tom:
> Hi iedereen, Lucas kan niet verder en Lee en Glen zijn hiervan al een tijdje op de hoogte. Ze gingen maken dat in het testnet er 100% synchronisatie kon gebeuren, vandaag blocked die op 50% en dat is iets wat Glen en LEE gingen oplossen. Van zodra dat klaar is kan Lucas verder. Dit is echt geen slechte wil maar realiteit. Dus hoe sneller dit is opgelost langs jullie kant hoe sneller Lucas hier kan aan verder werken. Nu is hij zelf oplossingen ah zoeken en loopt hij hierop constant vast aangezien er geen oplossing komt, dus moet hij hiermee stoppen want dwz dat hij zowaar al 3 dagen  getest heeft en geen mm verder is dus dit lost niets op voor niemand. Voila guys, Let's go and solve this together!
