### ISSUE TITLE
Replace the Intercom feature in app support with email

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#384]
In stead of having a live chat, we should have one channel for incoming support requests. Support button in the app should lead to the following message:

Please use the Support Form to receive help from our team members. Filling up the form is going to help our team to resolve your issue fast and effective.

* Full name
* Email address
* On what subject do you need assistance? 
(choices)
  - ThreeFold Tokens
  - Blockchain Node
  - Farming
  - Purchasing capacity
  - ThreeFold App
  - Other (specify)
* What is your wallet address? (if applicable)
* What is your ThreeFold Farm ID? (if applicable)
* Upload screenshot of issue (if applicable) 
* Please explain what it is you need assistance with. 

SEND

Send button should send this form to support@threefold.tech 
In staging app first for review.

**Comment by RubenMattan** [comment]
Maureen will create a report card for this

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, Maureen is working on the message flow. Can you check the Support button in staging app and give your remarks? She would also like to know if there are any fields that you want to make mandatory. If so, please let us know which ones. Thanks in advance!

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, can you plz try again? Your app had to launch from scratch because it wasn't running in the background. The app was still processing the update when you pressed the "Support" button.

We'll make name, email address, subject and explanation mandatory.

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, this is ready to be tested in the staging app.

**Comment by sabrinasadik** [comment]
- After closing the form, you land on TF Tokens page. Should be on News page since that's where you started.
- Delete first step with instructions. Add instructions to the first question (name).
- Email address should be in email form. Right now it's mandatory but you can fill in random symbols and still go to the next step.
- If a field is nog applicable, you should just click 'next' in stead of 'skip'. Same with the 'upload picture' step.
- You should be able to both upload a picture or take a picture (for example of a broken node or whatever). 
- Each step should have a back button. Right now it's not the case with each step.  
- Add step X of XX to every page otherwise it seems endless.

**Comment by bart-at-mobicage** [comment]
1. Looks like a bug in iOS. We'll look into it.
2. Done
3. We'll add email validation
4. Not possible. The photo step cannot be submitted (green button) when there's no photo selected. So that's why there's the gray SKIP button. Which means we cannot have a back button since there are only 2 buttons possible.
5. Done
6. Not possible. See 4.
7. Done

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, remark 1 is fixed (https://github.com/our-city-app/mobicage-ios-client/commit/e0852f2908d186cabbf0690b7505817290575aa3) and will be available in the next iOS release , but we'll need the ThreeFold Apple Developer Account to be ready first.

**Comment by sabrinasadik** [comment]
Ok, one more thing, can we change 'thank you' button at the end to just 'OK'?

**Comment by bart-at-mobicage** [comment]
> Ok, one more thing, can we change 'thank you' button at the end to just 'OK'?

Done
