### ISSUE TITLE
Wallet not working

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#385]
Wallet seems to give an unknown error 
No update in appstore / playstore available
Both IOS & Android

**Comment by sabrinasadik** [comment]
![2019-01-17 14 17 53](https://user-images.githubusercontent.com/31733464/51321376-dbe75980-1a62-11e9-82c4-328ed8325948.jpg)
![2019-01-17 14 18 06](https://user-images.githubusercontent.com/31733464/51321377-dbe75980-1a62-11e9-97fa-45336b1cd9b6.jpg)
![2019-01-17 14 18 10](https://user-images.githubusercontent.com/31733464/51321378-dbe75980-1a62-11e9-8a49-e9495c5b237b.jpg)

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, the wallet has been updated. This problem has been solved and the error message has been updated (#386).

**Comment by sabrinasadik** [comment]
Any action needed or can this be closed?
