### ISSUE TITLE
Create ThreeFold Apple/Google developer accounts

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#388]
@sabrinasadik and @VonSub 

Since the old developer account has expired last Monday, we urgently need the developer accounts for TF. An Apple developer account and a Google developer account. You can either give us the username/password so we can configure admin rights ourselves, or you can give me admin rights.

The staging app couldn't be moved to another account since that app wasn't published, so we need to create a new app on the new developer account. This is blocking the delivery of the test version of the ERC20 feature #383.

**Comment by sabrinasadik** [comment]
Application rejected: TF Tech needs an own website, this is in progress.

**Comment by bart-at-mobicage** [comment]
Hi @sabrinasadik and @VonSub,

To be able to transfer the Android apps I need to have the "Order ID for the target Play Console account's registration". The info from the e-mail that Roel provided didn't work (always the error "The transaction ID does not match for this developer account"), so I suggest to try to find the transaction ID via Google Payments using these instructions:

> If you can’t find the transaction ID email receipt:
> 
> 1. With the target account owner's email address, sign in to [Google Payments](https://payments.google.com/payments/home).
> 2. On the left menu, select Subscriptions and services.
> 3. On the “Other purchase activity” card, select View purchases.
> 4. Select the “Google Play” (or "Android Market") registration transaction.

source: https://support.google.com/googleplay/android-developer/answer/6230247?hl=en

**Comment by VonSub** [comment]
Both done. thanks for the help @bart-at-mobicage
