### ISSUE TITLE
Blockchain Nodes no longer visible in TF app

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#389]
@andhartl got a new phone. used seed key to get access. Worked fine, tokens are available in the wallet, but 2 BC nodes are not showing. 

![pastedgraphic](https://user-images.githubusercontent.com/31733464/51612391-a7bbdf00-1f21-11e9-8fa8-140f9c7761c0.jpg)

**Comment by andhartl** [comment]
thank you very much. solved.
