### ISSUE TITLE
App doesn't support coin creation transaction

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#390]
The farmers can't see their tokens on the mobil app.

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, is this 'creation transaction' different than other transactions?

Peter, Steven and Lucas can see their tokens

**Comment by sabrinasadik** [comment]
Examples: 016bed52adc96ec450559aad8cac821e4075023df8a3532b171aab504d664a8814f6f96f01c3d5 (see screenshots of this one)

011403698dc679749321edacc2fdfa7343095110a99ba83e4f73d0bfc4ffdb028a511ce44c7e0a

**Comment by sabrinasadik** [comment]
![Screenshot_2019-04-24-10-04-14](https://user-images.githubusercontent.com/31733464/56661201-8940bd80-66a1-11e9-8773-fd4e3a8ddae8.jpeg)
![Screenshot_2019-04-24-10-04-39](https://user-images.githubusercontent.com/31733464/56661202-89d95400-66a1-11e9-9f50-019f4b45fb59.jpeg)

**Comment by sabrinasadik** [comment]
This is about farmers, not the node hosters

**Comment by lucasvanhalst** [comment]
Fixed on staging
