### ISSUE TITLE
Registration fee for erc20 address not properly shown in transactions overview

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tf_app#392]
![image](https://user-images.githubusercontent.com/22023708/56671235-90bd9200-66b4-11e9-853b-942fd1a7f5ec.png)

the erc20 address registration (second tx from bottom) shows 0 TFT as sent, while the fee is 10 TFT (+0.1 TFT tx fee)

**Comment by lucasvanhalst** [comment]
Should be fixed
