### ISSUE TITLE
unrecognized hash used as input to /explorer/hash

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/tf_app#393]
![2019-05-03 09 34 32](https://user-images.githubusercontent.com/17762105/57124607-ae5ebb80-6d86-11e9-8fc9-9b3855c463de.jpg)

**Comment by bart-at-mobicage** [comment]
Multiple reports received.

![2019-05-07 09 46 03](https://user-images.githubusercontent.com/17762105/57282268-fc3c3200-70ac-11e9-97d3-cf5315cf34f5.jpg)

**Comment by bart-at-mobicage** [comment]
It looks like these users haven't automatically downloaded the latests version(s) of the wallet app. We're going to add an info button to the start page of the wallet, which will show some version info. If you ask for a screenshot of this info when a user has a problem, then this would help us very much.

**Comment by bart-at-mobicage** [comment]
Still occurred with wallet version `7b425b4`

**Comment by sabrinasadik** [comment]
App version 2.1.5245.a

**Comment by lucasvanhalst** [comment]
Should be fixed for real now (version from today 15:52). Let me know if it isn't
