### ISSUE TITLE
Remove live chat in tf app & replace with tf support link

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#400]
1. Delete Intercom chat in TF app.
2. When clicking on 'Support', customer should receive the following message:

We have created a new ticketing system, ThreeFold Support Center (TSC), which allows us to support users of ThreeFold technology in a controlled and efficient manner. 

The TSC ticketing system is meant for all deployments and users of TF technology including TF Grid, software, and/or token-related issues. 

Want to log a support issue or contact us? 

Visit the ThreeFold Support Center, log in with your 3Bot, and click on ‘Submit a ticket.’ You can even follow the process of your ticket on this platform. Fast, easy, and safe. 

(button - Log an issue - redirecting them to support.grid.tf

**Comment by bart-at-mobicage** [comment]
@sabrinasadik, this page is now visible in the TF staging and production app.
