### ISSUE TITLE
Wallet error

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tf_app#407]
Wallet address: 01e0b905bcdf527ce28bcec79d67003f5a4d5e857f3375b09ee799549af8941e49d7fc8e9aca1c)
App finds the transactions, but still gives an error and does not display the total token amount
![2019-10-30 12 06 35](https://user-images.githubusercontent.com/31733464/67852991-c7fe7700-fb0d-11e9-9413-4dbfef56d561.jpg)

**Comment by lucasvanhalst** [comment]
Updated the wallet, does it still happen now?

**Comment by LeeSmet** [comment]
Still happens, only now the transactions are not shown anymore either, just saying there is an unknown error

**Comment by lucasvanhalst** [comment]
updated timeout to 60 sec now
